DELIMITER //

CREATE TRIGGER TR_ACTUALIZAR_DETALLE_RESERVACION
AFTER UPDATE ON RESERVACION
FOR EACH ROW
BEGIN
    IF NEW.ESTADO_RESERVACION = 'CANCELADA' THEN
        UPDATE DETALLE_RESERVACION
        SET
            FECHA_INICIO = '0000-00-00 00:00:00',
            FECHA_FIN = '0000-00-00 00:00:00'
        WHERE
            RESERVACION = NEW.ID_RESERVACION;
    END IF;
END//

DELIMITER ;



DELIMITER //

CREATE TRIGGER ACTUALIZAR_ESTADO_RESERVACION_DESPUES_UPDATE
AFTER UPDATE ON DETALLE_RESERVACION
FOR EACH ROW
BEGIN
    IF (SELECT ESTADO_RESERVACION FROM RESERVACION WHERE ID_RESERVACION = NEW.RESERVACION) != 'CANCELADA' THEN
        UPDATE RESERVACION
        SET ESTADO_RESERVACION = 'activa'
        WHERE ID_RESERVACION = NEW.RESERVACION;
    END IF;
END;
//

DELIMITER ;